# 1. copy this file under name application.yml (mentioned in .gitignore to prevent from committing)
# 2. fill it up with the secrets and configuration

dkjs:
  # PROD, DEV or CI (github actions) - appended to the alert emails sent from the system
  environment: DEV

spring:
  profiles:
    # separated by comma:
    #  standard-time - to be set on production, exclusive with compressed-time
    #  compressed-time - should be used also for development and CI
    #  security - enables security - login window, not necessary during development
    #             but should be enabled on production and test system
    active:

  # standard SMTP settings
  # note: using it with GMail requires enabling access to less-safe apps
  # for more comprehensive setup, e.g. connection timeouts, refer to spring boot documentation
  mail:
    host:
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

documents:
  # base URL of the website holding pre-generated survey PDF documents
  urlBase: https://www.auf-leben.org/evaluation/

mail:
  # the email address from which surveys mails are being sent
  from:
  # the email address of the mailbox receiving alert messages
  sendAlertsTo:

typeform:
  # typeform client id - API key
  clientId:
  # base URL of typeform forms
  urlBase:
  forms:
    impuls: LZewTxb9
    pre: PoPWc4nm
    post: IGz0ULpp
    goalGPre: XYMjbimk
    goalGPost: W1x2LslZ

# Required by WebSecurityConfig to enable authentication.
# Gotcha: the password should identify the encoder, e.g.:
# - "{noop}hunter7"
# - "{bcrypt}$2a$12$v1C5OQYqGvD./dFy9eQcV.h9qj.X1lN/K0X4ISVcwPnfTYqXmZO0a"
# Both of these values configure credentials with a password "hunter7"
credentials:
  username:
  password:

time:
  timeZone: Europe/Berlin
  # applied only for profile test, value 1 -> 1 day = 1s; 60 -> 1 day = 1m
  dayDurationAsNumberOfSeconds: 1

# enable logging on DEV and PROD servers
#logging:
#  file:
#    path: logs
