# copy this file under name application.yml (in .gitignore to prevent from committing secrets)
# fill it up with the secrets

typeform:
  clientId:

# Required by WebSecurityConfig to enable authentication.
# Gotcha: the password should identify the encoder, e.g.:
# - "{noop}hunter7"
# - "{bcrypt}$2a$12$v1C5OQYqGvD./dFy9eQcV.h9qj.X1lN/K0X4ISVcwPnfTYqXmZO0a"
# Both of these values configure credentials with a password "hunter7"
credentials:
  username:
  password:

# note, using it with Gmail this way requires enabling access to less-safe apps
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          # TLS , port 587
          starttls:
            enable: true
#          # SSL, post 465
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory
