typeform:
  clientId: foo
  linkBase: https://typeform
mail:
  from: test@xemantic.com
  subject: Foo
  template: fadsfadf

spring:
#  config:
#    activate:
#      on-profile: test
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

---
