spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:db/dkjs
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    session:
      persistent: false
