mail:
  from: test@xemantic.com
  templateDir: src/main/resources/templates/

documents:
  linkBase: https://dkjs.de
  pdfURL: "%s?TODO_PDF=%s"

typeform:
  clientId: 4Z1CzeQcqricrsDxSbNLQPGyqHYYWgJ2VzVQM3WckUdr
  clientSecret: 5WTbd9Y7ZNy8ytmQUftDUoLBznz8Crcbnoe6NMfqA63B
  formId: fBwJApPU
  linkBase: https://typeform-todo.com
  surveyURL: "%s?projectNumber=%s&blocks=%s"

spring:
  profiles:
    active: prod
  mail:
    host: smtp.mailgun.org
    port: 587
    username: postmaster@sandbox0e985b1d535749f4ab94920d21c709fe.mailgun.org
    password: 3ed9c6055b5da2db61568018fb4b6640
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
#    test-connection: false
#    activate:
#      on-profile: test
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

server:
  servlet:
    session:
      persistent: false
