mail:
  from: test@xemantic.com
  templateDir: src/mail

documents:
  linkBase: https://dkjs.de

typeform:
  clientId: 1234
  formId: j6aFWMgy
  linkBase: https://typeform

spring:
  profiles:
    active: prod
  #  profiles:
  #  config:port: 2525
#    properties:
#      mail:
#        debug: false
#        smtp:
#          debug: false
#          auth: true
#          starttls: true
#    protocol: smtp
#    test-connection: false
#    activate:
#      on-profile: test
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

server:
  servlet:
    session:
      persistent: false
