spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          # TLS , port 587
          starttls:
            enable: true
#          # SSL, post 465
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory



