name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        env:
          TYPEFORM_CLIENT_ID: ${{ secrets.TYPEFORM_CLIENT_ID }}
          SPRING_PROFILES_ACTIVE: ci
        run: ./gradlew build
